### ISSUE TITLE
Node issue

### ISSUE THREAD

**Issue by DanjBethel** [MiniCodeMonkey/Vagrant-Laravel-Stack#16]
Now receiving this error. Seems to be in the npm modules section of the cookbooks. Just installed this two days ago and worked fine.

npm ERR! Error: SELF_SIGNED_CERT_IN_CHAIN
npm ERR!     at SecurePair.<anonymous> (tls.js:1350:32)
npm ERR!     at SecurePair.EventEmitter.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:963:10)
npm ERR!     at CleartextStream.read [as _read](tls.js:463:15)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:320:10)
npm ERR!     at EncryptedStream.write [as _write](tls.js:366:25)
npm ERR!     at doWrite (_stream_writable.js:219:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:209:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
npm ERR!     at write (_stream_readable.js:573:24)
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

**Comment by MiniCodeMonkey** [comment]
This seems to be an NPM issue. Is this still occurring to you?

**Comment by DanjBethel** [comment]
Haven't tried of since then. Will do then get back to you.

**Comment by DanjBethel** [comment]
Works fine now.

**Comment by MiniCodeMonkey** [comment]
Sounds good!--
Mathias Hansen

**Comment by DanjBethel** [comment]
That issue is fixed, but now I'm getting a (delayed) message on my mysql, memcached and postgres stuff. Says it's already qued?

[2014-03-05T19:13:29+00:00] INFO: execute[a2dissite default] sending restart action to service[apache2](delayed)
[2014-03-05T19:13:33+00:00] INFO: service[apache2] restarted
[2014-03-05T19:13:33+00:00] INFO: template[/etc/memcached.conf] sending restart action to service[memcached](delayed)
[2014-03-05T19:13:33+00:00] INFO: service[memcached] restarted
[2014-03-05T19:13:33+00:00] INFO: template[/etc/default/beanstalkd] sending restart action to service[beanstalkd](delayed)
[2014-03-05T19:13:36+00:00] INFO: service[beanstalkd] restarted
[2014-03-05T19:13:36+00:00] INFO: template[/etc/mysql/debian.cnf] sending reload action to service[mysql](delayed)
[2014-03-05T19:13:37+00:00] INFO: service[mysql] reloaded
[2014-03-05T19:13:37+00:00] INFO: template[/etc/postgresql/9.3/main/environment] sending restart action to service[postgresql](delayed)
[2014-03-05T19:13:40+00:00] INFO: service[postgresql] restarted
[2014-03-05T19:13:40+00:00] INFO: template[/etc/postfix/main.cf] sending restart action to service[postfix](delayed)
[2014-03-05T19:13:41+00:00] INFO: service[postfix] restarted
[2014-03-05T19:13:41+00:00] INFO: Chef Run complete in 2233.085277485 seconds

**Comment by MiniCodeMonkey** [comment]
That's not an error, it just means that they're pending restart. You should safely be able to ignore those. --
Mathias Hansen

**Comment by DanjBethel** [comment]
Yes. That's what I assumed but I notice I can't connect successfully to
mysql
