### ISSUE TITLE
Solve::Errors::InvalidVersionFormat

### ISSUE THREAD

**Issue by pacuna** [MiniCodeMonkey/Vagrant-Laravel-Stack#9]
After running vagrant up I'm getting this error:

``` ruby
Bringing machine 'laravel' up with 'virtualbox' provider...
[laravel] Importing base box 'precise64'...
[laravel] Matching MAC address for NAT networking...
[laravel] Setting the name of the VM...
[laravel] Clearing any previously set forwarded ports...
[laravel] Destroying VM and associated drives...
[laravel] Running cleanup tasks for 'hostmanager' provisioner...
[laravel] Running cleanup tasks for 'shell' provisioner...
[laravel] Running cleanup tasks for 'shell' provisioner...
[laravel] Running cleanup tasks for 'chef_solo' provisioner...
/home/pacuna/.vagrant.d/gems/gems/solve-0.8.1/lib/solve/version.rb:20:in `split': '1.3.6.dev' did not contain a valid version string: 'x.y.z' or 'x.y
'. (Solve::Errors::InvalidVersionFormat)
        from /home/pacuna/.vagrant.d/gems/gems/solve-0.8.1/lib/solve/version.rb:55:in `initialize'
        from /home/pacuna/.vagrant.d/gems/gems/solve-0.8.1/lib/solve/constraint.rb:190:in `new'
        from /home/pacuna/.vagrant.d/gems/gems/solve-0.8.1/lib/solve/constraint.rb:190:in `satisfies?'
        from /home/pacuna/.vagrant.d/gems/gems/vagrant-berkshelf-1.3.4/lib/berkshelf/vagrant/action/install.rb:57:in `check_vagrant_version'
        from /home/pacuna/.vagrant.d/gems/gems/vagrant-berkshelf-1.3.4/lib/berkshelf/vagrant/action/install.rb:41:in `install'
        from /home/pacuna/.vagrant.d/gems/gems/vagrant-berkshelf-1.3.4/lib/berkshelf/vagrant/action/install.rb:30:in `call'
        from /home/pacuna/.rvm/gems/ruby-1.9.3-p448/gems/vagrant-1.3.6.dev/lib/vagrant/action/warden.rb:34:in `call'
        from /home/pacuna/.rvm/gems/ruby-1.9.3-p448/gems/vagrant-1.3.6.dev/lib/vagrant/action/builtin/provision.rb:54:in `call'
        from /home/pacuna/.rvm/gems/ruby-1.9.3-p448/gems/vagrant-1.3.6.dev/lib/vagrant/action/warden.rb:34:in `call'
        from /home/pacuna/.rvm/gems/ruby-1.9.3-p448/gems/vagrant-1.3.6.dev/plugins/providers/virtualbox/action/clear_forw
```

**Comment by MiniCodeMonkey** [comment]
Might have been a temporary issue with that particular cookbook. Please try again.
